upstream core_upstream {
    server core:8080;
}

upstream auth_upstream {
    server auth:8082;
}

upstream files_upstream {
    server files:8084;
}

upstream notification_upstream {
    server notification:8083;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 25m;

    location = /health/nginx {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "OK";
    }

    location /api/auth/ {
        proxy_pass http://auth_upstream/api/auth/;
        include /etc/nginx/proxy_params;
    }

    location /auth/ {
        proxy_pass http://auth_upstream/api/auth/;
        include /etc/nginx/proxy_params;
    }

    location /api/files/ {
        proxy_pass http://files_upstream/api/files/;
        include /etc/nginx/proxy_params;
    }

    location /files/ {
        proxy_pass http://files_upstream/api/files/;
        include /etc/nginx/proxy_params;
    }

    location /internal/notification/actuator/health {
        proxy_pass http://notification_upstream/actuator/health;
        include /etc/nginx/proxy_params;
    }

    location /internal/files/actuator/health {
        proxy_pass http://files_upstream/actuator/health;
        include /etc/nginx/proxy_params;
    }

    location /internal/core/actuator/health {
        proxy_pass http://core_upstream/actuator/health;
        include /etc/nginx/proxy_params;
    }

    location / {
        proxy_pass http://core_upstream;
        include /etc/nginx/proxy_params;
    }
}
